bucket_no_upscale = true
bucket_reso_steps = 64
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 1
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 0.0001
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 160
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 1600
min_bucket_reso = 512
mixed_precision = "fp16"
multires_noise_discount = 0.3
network_alpha = 1
network_args = []
network_dim = 32
network_module = "networks.lora"
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "./test_lora_unet_clip_0628"
output_name = "last"
pretrained_model_name_or_path = "/root/albertxyu/HunYuanDiT-V1.1-fp16-pruned"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "/root/albertxyu/kohya_ss/outputs/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
text_encoder_lr = 0.0001
train_batch_size = 1
train_data_dir = "/root/albertxyu/sd-scripts/train_data"
unet_lr = 0.0001
v_parameterization = true
xformers = true
save_every_n_steps = 50